name             'cespi_application'
maintainer       'Christian A. Rodriguez & Leandro Di Tommaso'
maintainer_email 'car@cespi.unlp.edu.ar lditommaso@cespi.unlp.edu.ar'
license          'All rights reserved'
description      'Provides resources for almost any CeSPI application'
long_description 'Installs/Configures cespi_application'
version          '0.1.1'

depends         'mysql', '=5.4.0'
depends         'database', '=2.3.0'
